nginx:
  image: nginx
  volumes:
    - ./conf.d:/etc/nginx/conf.d
  volumes_from:
    - nginx-data
  ports:
    - "80:80"
  net: host

nginx-data:
  image: nginx
  volumes:
    - /var/log/nginx
  command: ls /var/log/nginx

# vim:set et ts=2 sw=2:
