#!/usr/bin/env bash

if [ ! "$2" ];then
    cat << EOF
Usage: $0 <FQDN> <URL>

For example:

	$0 parse.example.com http://localhost:1337
EOF
exit 1
fi

cat << EOF
server {
    listen       80;
    server_name  $1;

    location / {
        proxy_pass "$2";
    }
}
EOF
